name: pistis_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  flutter_riverpod: ^2.6.1
  drift: ^2.26.1
  supabase_flutter: ^2.9.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  flutter_local_notifications: ^19.2.1
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/pistis.png
  min_sdk_android: 21 

# flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  color: "#000000"
  image: assets/images/pistis.png
  fullscreen: true
  android_gravity: center
  ios_content_mode: center
  android: true
  ios: true
  web: false

# flutter pub run flutter_native_splash:remove
# flutter pub run flutter_native_splash:create

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/